
-- 모든 테이블 데이터 삭제

SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM reply;
ALTER TABLE reply AUTO_INCREMENT = 1;

DELETE FROM qna;
ALTER TABLE qna AUTO_INCREMENT = 1;

DELETE FROM wishlist;
ALTER TABLE wishlist AUTO_INCREMENT = 1;

DELETE FROM skin_profile;
ALTER TABLE skin_profile AUTO_INCREMENT = 1;

DELETE FROM cart;
ALTER TABLE cart AUTO_INCREMENT = 1;

DELETE FROM post_hashtag;
ALTER TABLE post_hashtag AUTO_INCREMENT = 1;

DELETE FROM post_product;
ALTER TABLE post_product AUTO_INCREMENT = 1;

DELETE FROM product_image;
ALTER TABLE product_image AUTO_INCREMENT = 1;

DELETE FROM product_hashtag;
ALTER TABLE product_hashtag AUTO_INCREMENT = 1;

DELETE FROM `like`;
ALTER TABLE `like` AUTO_INCREMENT = 1;

DELETE FROM order_item;
ALTER TABLE order_item AUTO_INCREMENT = 1;

DELETE FROM payment;
ALTER TABLE payment AUTO_INCREMENT = 1;

DELETE FROM post;
ALTER TABLE post AUTO_INCREMENT = 1;

DELETE FROM product;
ALTER TABLE product AUTO_INCREMENT = 1;

DELETE FROM `order`;
ALTER TABLE `order` AUTO_INCREMENT = 1;

DELETE FROM mem;
ALTER TABLE mem AUTO_INCREMENT = 1;

DELETE FROM hashtag;
ALTER TABLE hashtag AUTO_INCREMENT = 1;

DELETE FROM category;
ALTER TABLE category AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;